In [1]:
%load_ext autoreload
%autoreload 2
import sys

sys.path.append("..")

In [2]:
import json
from time import perf_counter

import torch
from llama_python.configuration import LlamaConfig
from llama_python.model import LlamaForCausalLM, LlamaModel
from llama_python.tokenizer import PreTrainedTokenizerFast
from transformers import AutoTokenizer

from pycallm.lib import pycallm

tokenizer_config: dict = json.load(open("../resources/original_llama/tokenizer_config.json", "r"))
model_config: dict = json.load(open("../resources/original_llama/config.json", "r"))

encoder_file = "../resources/tokenizer.model"
cache_dir = "../hf-cache"
model_config_path = "../config.json"
model_weights_path = "../model2.safetensors"

secrets = json.load(open("../secrets.json", "r"))
hf_token = secrets["hf"]["token"]

In [3]:
tokenizer = pycallm.Tokenizer(encoder_file)

In [ ]:
llm = pycallm.LLamaModel(model_weights_path, model_config_path)

## Tokenization

In [ ]:
token_ids = tokenizer.tokenize("Je ne pense pas qu'il y ai de bonnes ou de mauvaises situations...")
res = llm.embed(token_ids)

In [7]:
token_ids

[30854,
 841,
 73953,
 6502,
 934,
 35329,
 379,
 16796,
 409,
 7970,
 4978,
 6033,
 409,
 60014,
 85,
 22626,
 15082,
 1131]

In [8]:
res

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,


In [3]:
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B-Instruct", cache_dir=cache_dir, token=hf_token)

In [4]:
t0 = perf_counter()
tokenizer.encode("Je ne pense pas qu'il y ai de bonnes ou de mauvaises situations...")
(perf_counter() - t0) * 1_000_000

71095.56299838005

In [38]:
t0 = perf_counter()
callm_tokenizer.tokenize("Je ne pense pas qu'il y ai de bonnes ou de mauvaises situations...")
res = perf_counter() - t0

 Min rank: 296; Min size: 0; Parts len: 9
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:591 in byte_pair_encode(): Min rank: 296; Min size: 0; Parts len: 9
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:610 in byte_pair_encode(): END Min rank: 2852; Min size: 4; Parts len: 8
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:591 in byte_pair_encode(): Min rank: 2852; Min size: 4; Parts len: 8
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:610 in byte_pair_encode(): END Min rank: 2933; Min size: 1; Parts len: 7
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:591 in byte_pair_encode(): Min rank: 2933; Min size: 1; Parts len: 7
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:610 in byte_pair_encode(): END Min rank: 22626; Min size: 3; Parts len: 6
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:591 in 

In [14]:
res = llm.embed(token_ids)

In [41]:
callm_tokenizer.get_token_by_id(7970), callm_tokenizer.get_token_by_id(220), callm_tokenizer.get_token_by_id(409)

projects/ai/callm/src/tokenizer/tokenizer.c:651 in Tokenizer_encode(): ========== ' bonnes' ===========
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:660 in Tokenizer_encode(): Token not found:  bonnes
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:548 in byte_pair_encode(): Pair:  b - Not found in encoder
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:548 in byte_pair_encode(): Pair: bo - Not found in encoder
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:548 in byte_pair_encode(): Pair: on - Not found in encoder
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:548 in byte_pair_encode(): Pair: nn - Not found in encoder
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:548 in byte_pair_encode(): Pair: ne - Not found in encoder
[DEBUG] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:548 in byte_pair_encode(

(' bon', ' ', ' de')


[INFO] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:248 in Tokenizer_new(): Encoder created. Creating decoder
[INFO] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:255 in Tokenizer_new(): Decoder created. Compiling ordinary tokens regex
[INFO] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:233 in Tokenizer_new(): Creating encoder from file
[INFO] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:241 in Tokenizer_new(): Creating encoder...
[INFO] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:248 in Tokenizer_new(): Encoder created. Creating decoder
[INFO] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:255 in Tokenizer_new(): Decoder created. Compiling ordinary tokens regex
[INFO] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c:233 in Tokenizer_new(): Creating encoder from file
[INFO] /home/thomas/Documents/projects/ai/callm/src/tokenizer/tokenizer.c

In [14]:
tokenizer = PreTrainedTokenizerFast(
    name_or_path='meta-llama/Llama-3.2-1B-Instruct', 
    vocab_file=encoder_file,
    vocab_size=128000, 
    model_max_length=131072, 
    is_fast=True, 
    padding_side='right', 
    truncation_side='right', 
    special_tokens={'bos_token': '<|begin_of_text|>', 'eos_token': '<|eot_id|>'}, 
    clean_up_tokenization_spaces=True, 
    added_tokens_decoder={}
)

```
[30854, 841, 73953, 6502, 934, 35329, 379, 107902, 409, 220, 65, 78, 77, 77, 68, 82, 6033, 409, 220, 76, 64, 84, 85, 64, 72, 82, 68, 82, 15082, 1131]

[30854, 841, 73953, 6502, 934, 35329, 379, 107902, 409, 7970, 4978, 6033, 409, 60014, 85, 22626, 15082, 1131]

[30854, 841, 73953, 6502, 934, 35329, 379, 107902, 409, 7970, 4978, 6033, 409, 60014, 85, 22626, 15082, 1131]
```

In [35]:
pycallm.tokenize(encoder_file, "bo")

[754]

In [42]:
tokenizer.encode("bo")

[754]

In [15]:
tokenizer.encode("Je ne pense pas qu'il y ait de bonnes ou de mauvaises situations...")

[30854,
 841,
 73953,
 6502,
 934,
 35329,
 379,
 107902,
 409,
 7970,
 4978,
 6033,
 409,
 60014,
 85,
 22626,
 15082,
 1131]

## Model

In [5]:
model_config = LlamaConfig(**model_config)

In [6]:
model = LlamaForCausalLM(model_config)

In [7]:
from safetensors.torch import load_file
import torch

state_dict = load_file("../model2.safetensors")

list(state_dict.keys())

In [8]:
if "lm_head.weight" not in state_dict:
    model.lm_head.weight = model.get_input_embeddings().weight

In [9]:
missing_keys, unexpected_keys = model.load_state_dict(state_dict, strict=False)
print("Missing keys:", missing_keys)
print("Unexpected keys:", unexpected_keys)

Missing keys: ['lm_head.weight']
Unexpected keys: []


In [10]:
inputs = tokenizer("Je ne pense pas qu'il y ai de bonnes ou de mauvaises situations...", return_tensors="pt")
inputs

{'input_ids': tensor([[128000,  30854,    841,  73953,   6502,    934,  35329,    379,  16796,
            409,   7970,   4978,   6033,    409,  60014,     85,  22626,  15082,
           1131]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

### Experiments

In [14]:
A = torch.Tensor([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
])
torch.cat((A, A), dim=1).cos()

tensor([[ 0.5403, -0.4161, -0.9900,  0.5403, -0.4161, -0.9900],
        [ 0.5403, -0.4161, -0.9900,  0.5403, -0.4161, -0.9900],
        [ 0.5403, -0.4161, -0.9900,  0.5403, -0.4161, -0.9900],
        [ 0.5403, -0.4161, -0.9900,  0.5403, -0.4161, -0.9900],
        [ 0.5403, -0.4161, -0.9900,  0.5403, -0.4161, -0.9900]])

In [36]:
import torch
from torch import nn, Tensor

class Test(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(in_features=3, out_features=4, bias=False)

    def forward(self, input):
        res = self.layer(input)
        return res


model = Test()
state = {
    "layer.weight": Tensor([
        [1, 2, 3],
        [10, 20, 30],
        [100, 200, 300],
        [1000, 2000, 3000],
    ])
}
model = Test()
model.load_state_dict(state)
print(model.state_dict())

input_data = Tensor([
    [1, 1, 1],
    [2, 2, 2],
])



print(input_data.shape)
with torch.no_grad():
    res = model(input_data)
    print(res, res.shape)

OrderedDict({'layer.weight': tensor([[1.0000e+00, 2.0000e+00, 3.0000e+00],
        [1.0000e+01, 2.0000e+01, 3.0000e+01],
        [1.0000e+02, 2.0000e+02, 3.0000e+02],
        [1.0000e+03, 2.0000e+03, 3.0000e+03]])})
torch.Size([2, 3])
tensor([[6.0000e+00, 6.0000e+01, 6.0000e+02, 6.0000e+03],
        [1.2000e+01, 1.2000e+02, 1.2000e+03, 1.2000e+04]]) torch.Size([2, 4])


In [55]:
data = torch.arange(60).reshape((6, 10))
#data = torch.broadcast_to(data, (6, 10))
data, data.view((6, -1, 5)), data.view((6, -1, 5)).transpose(0, 1)

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9]],
 
         [[10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]],
 
         [[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29]],
 
         [[30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]],
 
         [[40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49]],
 
         [[50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59]]]),
 tensor([[[ 0,  1,  2,  3,  4],
          [10, 11, 12, 13, 14],
          [20, 21, 22, 23, 24],
          [30, 31, 32, 33, 34],
          [40, 41, 42, 43, 44],
          [50, 51, 52, 53, 54]],
 
         [[ 5,  6,  7,  8,  9],
          [15, 16, 17, 18, 19],
          [25, 26, 27, 28, 29],

In [38]:
data = Tensor([
    [1, 2, 3, 4, 5, 6],
    [10, 20, 30, 40, 50, 60],
    [100, 200, 300, 400, 500, 600],
])
hidden_shape = (3, -1, 2)
data.view(hidden_shape)

tensor([[[  1.,   2.],
         [  3.,   4.],
         [  5.,   6.]],

        [[ 10.,  20.],
         [ 30.,  40.],
         [ 50.,  60.]],

        [[100., 200.],
         [300., 400.],
         [500., 600.]]])

In [73]:
(torch.arange(6) * 2).tolist()

[0, 2, 4, 6, 8, 10]

In [77]:
# query_states torch.Size([1, 32, 11, 64])

x = Tensor([
    [
        [
            (torch.arange(6) * 1).tolist(),
            (torch.arange(6) * 2).tolist(),
            (torch.arange(6) * 3).tolist(),
            (torch.arange(6) * 4).tolist(),
        ]
    ],
    [
        [
            (torch.arange(6) * 10).tolist(),
            (torch.arange(6) * 20).tolist(),
            (torch.arange(6) * 30).tolist(),
            (torch.arange(6) * 40).tolist(),
        ]
        
    ],
    [
        [
            (torch.arange(6) * 100).tolist(),
            (torch.arange(6) * 200).tolist(),
            (torch.arange(6) * 300).tolist(),
            (torch.arange(6) * 400).tolist(),
        ]
        
    ]
])
print(x.shape)
y = x[...,  x.shape[-1]//2 :]
#y = x[..., : x.shape[-1]//2]
y = x[x.shape[-1]//2 :, ...]kkk
print(y.shape)
y

torch.Size([3, 1, 4, 6])
torch.Size([0, 1, 4, 6])


tensor([], size=(0, 1, 4, 6))

### Run model

In [11]:
model(**inputs)

======== LlamaModel.forward =========
input_ids shape= torch.Size([1, 19])
output_attentions False
output_hidden_states False
use_cache True
return_dict True
not in training mode
inputs_embeds torch.Size([1, 19, 2048])
init dynamic cache
init cache_position
past_seen_tokens 0
cache_position shape torch.Size([19])
cache_position tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18])
unsequeeze position_ids...
position_ids None
after unsqueeze position_ids shape torch.Size([1, 19])
position_ids tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18]])
======== _update_causal_mask =========
attention implementation sdpa
sdpa
>>>>>>>> LlamaModel.forward
======== LlamaRotaryEmbedding.forward =========
rope_type llama3
inv_freq shape torch.Size([32])
inv_freq tensor([1.0000e+00, 6.6360e-01, 4.4037e-01, 2.9223e-01, 1.9392e-01, 1.2869e-01,
        8.5397e-02, 5.6670e-02, 3.7606e-02, 2.4955e-02, 1.6560e-02, 1.0990e-02,


CausalLMOutputWithPast(loss=None, logits=tensor([[[ 7.0544,  9.0268, 13.3233,  ..., -3.7595, -3.7596, -3.7596],
         [ 8.8571,  6.3757,  5.3784,  ..., -2.6351, -2.6340, -2.6338],
         [10.5552,  9.8011,  4.2687,  ..., -1.6779, -1.6772, -1.6774],
         ...,
         [ 9.6958,  8.1138,  4.2293,  ..., -2.1778, -2.1765, -2.1783],
         [14.4338, 13.2308, 11.2213,  ..., -0.5268, -0.5261, -0.5268],
         [14.0223, 10.1273, 11.0009,  ..., -1.6579, -1.6578, -1.6590]]],
       grad_fn=<UnsafeViewBackward0>), past_key_values=DynamicCache(), hidden_states=None, attentions=None)

In [18]:
res

CausalLMOutputWithPast(loss=None, logits=tensor([[[ 5.1046,  5.1268,  7.3774,  ..., -4.7377, -4.7379, -4.7383],
         [11.7675, 12.5821, 10.6723,  ...,  0.8230,  0.8236,  0.8231],
         [13.1911, 12.9374, 10.9242,  ..., -0.3592, -0.3591, -0.3589],
         ...,
         [12.0275, 10.4520, 10.9077,  ...,  0.8572,  0.8575,  0.8566],
         [11.2537,  9.2107,  7.9047,  ..., -1.3219, -1.3206, -1.3209],
         [10.4584,  8.6227,  9.6627,  ..., -1.7254, -1.7234, -1.7235]]],
       grad_fn=<UnsafeViewBackward0>), past_key_values=DynamicCache(), hidden_states=None, attentions=None)